In [1]:
import numpy as np

array1 = np.array([[1,2,3],
                [2,3,4]])
print (array1)
print ("number of dim:",array1.ndim)#是几维数组
print ('shape:',array1.shape)##是多少列
print ('size:',array1.size)##y有多少元素

[[1 2 3]
 [2 3 4]]
number of dim: 2
shape: (2, 3)
size: 6


In [2]:
import numpy as np

##a = np.array([2,23,4],dtype=np.int)##整数型
##a = np.array([2,23,4],dtype=np.float)##浮点型
#a = np.array([[2,23,4],
#             [2,32,4]])##矩阵
#a = np.zeros((3,4))#生产空矩阵
#a = np.arange(10,20,2)#10开始到20结束，步长为2
#a = np.arange(12).reshape((3,4))#生成3行4列数组
#a = np.linspace(1,10,20)#生产从1到20的2o段数列
a = np.linspace(1,10,6).reshape((2,3))
##print (a.dtype)
print (a)

[[ 1.   2.8  4.6]
 [ 6.4  8.2 10. ]]


In [42]:
import numpy as np

#a = np.array([10,20,30,40])
#a = np.array([[1,1],
 #            [0,1]])
a = np.random.random((2,4))
#b = np.arange(4).reshape((2,2))
#b = np.arange(4)
#print (a,b)

print (a)
#print (np.sum(a))
# print (np.sum(a,axis=1))#行求和
print (np.min(a,axis=0))#列求和
#print (np.max(a))
#c = a*b

# c_dot = np.dot(a,b)
#c_dot_2 = a.dot(b)#同上一句意思一样

#print (a)
#print (c)
#print (c_dot)
#print (c_dot_2)
##c = a- b
##c = a + b
#c = b**2
#c =  10*np.sin(a)
#print (c)
#print (b<3)##返回列表
#print (b==3)

[[0.4439481  0.1467039  0.71396203 0.06540045]
 [0.8132168  0.91174526 0.38081946 0.74953127]]
[0.4439481  0.1467039  0.38081946 0.06540045]


In [68]:
import numpy as np

# a = np.arange(2,14).reshape(3,4)
a = np.arange(14,2,-1).reshape(3,4)


# print (np.argmin(a))##列出最小值索引
# print (np.argmax(a))#列出最大值索引
# print (np.mean(a))#平均值
# print (np.average(a))#另一种平均值
# print (np.median(a))#中位数
# print (np.cumsum(a))#逐步累加
# print (np.diff(a))#累差
# print (np.nonzero(a))
# print (np.sort(a))#排序
# print(np.transpose(a))#行列转换
# print ((a.T))##同上句意思
# print ((a.T).dot(a))#矩阵乘法
# print (np.clip(a,5,9))#把矩阵中小于5的数变成5，大于9的数等于9
# print (np.mean(a,axis=0))#列平均值
print (np.mean(a,axis=1))#行平均值计算
# print (a)

[12.5  8.5  4.5]


In [94]:
# import numpy as np

a = np.arange(3,15).reshape(3,4)
print (a)
# print (a[2])
# print (a[1][1])#多维索引
# print (a[1,1])#同上句
# print (a[2,:])#同列表用法
# print (a[:,1])
# print (a[1,1:2])
# for row in a:
#     print (row)
# for column in a.T:##翻转后打印列
#     print (column)

print (a.flatten())#变成一行
for item in a.flat:#行迭代
    print (item)
# print (a[3])#s索引，同列表


[[ 3  4  5  6]
 [ 7  8  9 10]
 [11 12 13 14]]
[ 3  4  5  6  7  8  9 10 11 12 13 14]
3
4
5
6
7
8
9
10
11
12
13
14


In [113]:
import numpy as np

a = np.array([1,1,1])
b = np.array([2,2,2])

# print (np.vstack((a,b)))#vertical stack
# c = np.vstack((a,b))#c变为矩阵
# d = np.hstack((a,b))#horizontal stack
# print (d)
# print (a.shape,c.shape)
# print (a[np.newaxis,:])
print (a[:,np.newaxis])
c = np.concatenate((a[:,np.newaxis],b[:,np.newaxis]),axis=1)
print (c)

[[1]
 [1]
 [1]]
[[1 2]
 [1 2]
 [1 2]]


In [120]:
import numpy as np

a = np.arange(12).reshape((3,4))
print (a)
# print (np.split(a,2,axis= 1))
# print (np.split(a,3,axis = 0))
# print (np.array_split(a,3,axis = 1))##不等量分割
print (np.vsplit(a,3))
print (np.hsplit(a,2))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]
[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]


In [135]:
import numpy as np

a = np.arange(4)
print (a)
b = a
c = a
d = b
a[0] = 11
# print (a)
# print (b)
# print (c)
# print (b) is (a)
# print (d)
# d[1:3] = [22,33]
# print (a)
# print (c)
b = a.copy()#deep copy
print (b)
a[3] = 44
print (a)
print (b)

[0 1 2 3]
[11  1  2  3]
[11  1  2 44]
[11  1  2  3]
